spring:
  application:
    name: product_catalogue
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    name: logs/product_catalogue.log
    max-size: 2MB
    max-history: 5
  level:
    root: INFO
    com.learn.product_catalogue: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR      