spring:
  application:
    name: product_catalogue
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  pattern:
    # Colored pattern for console
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    # Plain pattern for file (no colors)
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n%wEx"
  file:
    name: logs/product_catalogue.log
    max-size: 2MB
    max-history: 5
  level:
    root: INFO
    com.learn.product_catalogue: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR      